server:
  port: 8899
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.tqk
#  type-aliases-package:
  # 打印出sql语句
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  profiles:
    active: dev
# 打印 sql语句使用
logging:
  level:
    com.lucifer.springboot.cache.mapper: debug